env = Environment(    
    LIBS = ['sfml-window','sfml-system','sfml-graphics', 'sfml-audio'],
    LIBPATH = ['/usr/lib', '/usr/local/lib'],
    CXXFLAGS="-std=c++0x -g")
env.Program('Snake.exe', Glob('*.cpp'))
